export const UserData = [
    {
      id: 1,
      pos: "03",
      Direct: 55,
      Organic: 25,
      Referral: 18,
      Social: 20,
    },
    {
      id: 2,
      pos: "04",
      Direct: 44,
      Organic: 16,
      Referral: 10,
      Social: 12,
    },
    {
      id: 3,
      pos: "05",
      Direct: 50,
      Organic: 24,
      Referral: 6,
      Social: 11,
    },
    {
      id: 4,
      pos: "06",
      Direct: 52,
      Organic: 15,
      Referral: 12,
      Social: 8,
    },
    {
      id: 5,
      pos: "07",
      Direct: 40,
      Organic: 14,
      Referral: 19,
      Social: 15,
    },
    {
      id: 6,
      pos: "08",
      Direct: 32,
      Organic: 6,
      Referral: 40,
      Social: 12,
    },
  ];